#   <font color="cyan">Loading the data</font>

In [1]:
#We will first import the libraries to be used
import pandas as pd

import numpy as np

In [23]:
# now we will read the csv 
df_a = pd.read_csv('Autolib_dataset.csv')

In [24]:
# now we will preview the dataset
df_a

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

In [25]:
# now understanding out data more 
df_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge_Slots         5000 non-null   int64
 6   Charging_Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed_comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo_point            5000 non-null   object
 12  Postal_code          5000 non-null   int64
 13  Public_name          5000 non-null   object
 14  Rental_status        5000 non-null   object
 15  Scheduled_at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station_type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription_status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

# <font color="cyan[link text](https://)">Data Cleaning</font>

## Validity

In [26]:
df_a.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [27]:
# correcting typos in order to get cleaner data 
df_a['Public_name'] = df_a['Public_name'].str.replace('Paris/EugÃ¨ne OudinÃ©/51', 'Eguisheim/Oudincourt')

In [28]:
#correcting typos \
df_a['Address'] = df_a['Address'].str.replace('EugÃ¨ne OudinÃ©', 'Eguisheim/Oudincourt')

In [44]:
df_a['Public_name'] = df_a['Public_name'].str.replace('MÃ©nelotte/8','Macnelotte')

In [45]:
df_a['Address'] = df_a['Address'].str.replace('MÃ©nelotte','Macnelotte')

In [48]:
# converting the date into the right format 
df_a['Date'] = df_a[df_a.columns[20:23]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)
df_a['Date'] = pd.to_datetime(df_a['Date'])

In [ ]:
df_a['Time'] = df_a[df_a.columns[23:25]].apply(
    lambda x: ':'.join(x.dropna().astype(str)),
    axis=1
)
df_a['Time'] = pd.to_datetime(df_a['Time'])

In [49]:
df_a

                                 Address  Cars  ...       Date   Time
0                    2 Avenue de Suffren     0  ... 2018-04-08  11:43
1              145 Rue Raymond Losserand     6  ... 2018-04-06   7:24
2       2 Avenue John Fitzgerald Kennedy     3  ... 2018-04-03  20:14
3            51 Rue Eguisheim/Oudincourt     3  ... 2018-04-04   4:37
4     6 avenue de la Porte de Champerret     3  ... 2018-04-08  17:23
...                                  ...   ...  ...        ...    ...
4995                 8 avenue Macnelotte     2  ... 2018-04-06  11:26
4996                   37 rue de Dantzig     4  ... 2018-04-04  16:56
4997                      142 rue du Bac     1  ... 2018-04-01    7:1
4998         2 avenue du Val de Fontenay     2  ... 2018-04-04  17:27
4999                 5 Rue Henry Brisson     4  ... 2018-04-08   10:2

[5000 rows x 27 columns]

##   Accuracy

In [ ]:
# N/A

##     Completenesss

In [43]:
df_a.value_counts()

Series([], dtype: int64)

In [ ]:
df_a.dropna(axis=0,how='all')

In [53]:
df_a.drop(['year',	'month','day','hour',	'minute','Scheduled_at','Geo_point','Displayed_comment'],
  axis= 1, inplace=True)

In [54]:
df_a

                                 Address  Cars  ...       Date   Time
0                    2 Avenue de Suffren     0  ... 2018-04-08  11:43
1              145 Rue Raymond Losserand     6  ... 2018-04-06   7:24
2       2 Avenue John Fitzgerald Kennedy     3  ... 2018-04-03  20:14
3            51 Rue Eguisheim/Oudincourt     3  ... 2018-04-04   4:37
4     6 avenue de la Porte de Champerret     3  ... 2018-04-08  17:23
...                                  ...   ...  ...        ...    ...
4995                 8 avenue Macnelotte     2  ... 2018-04-06  11:26
4996                   37 rue de Dantzig     4  ... 2018-04-04  16:56
4997                      142 rue du Bac     1  ... 2018-04-01    7:1
4998         2 avenue du Val de Fontenay     2  ... 2018-04-04  17:27
4999                 5 Rue Henry Brisson     4  ... 2018-04-08   10:2

[5000 rows x 19 columns]

##     Consistency

In [55]:
df_a = df_a.drop_duplicates()

##   Uniformity

In [56]:
df_a['Kind'] = df_a['Kind'].str.lower()

In [57]:
df_a

                                 Address  Cars  ...       Date   Time
0                    2 Avenue de Suffren     0  ... 2018-04-08  11:43
1              145 Rue Raymond Losserand     6  ... 2018-04-06   7:24
2       2 Avenue John Fitzgerald Kennedy     3  ... 2018-04-03  20:14
3            51 Rue Eguisheim/Oudincourt     3  ... 2018-04-04   4:37
4     6 avenue de la Porte de Champerret     3  ... 2018-04-08  17:23
...                                  ...   ...  ...        ...    ...
4995                 8 avenue Macnelotte     2  ... 2018-04-06  11:26
4996                   37 rue de Dantzig     4  ... 2018-04-04  16:56
4997                      142 rue du Bac     1  ... 2018-04-01    7:1
4998         2 avenue du Val de Fontenay     2  ... 2018-04-04  17:27
4999                 5 Rue Henry Brisson     4  ... 2018-04-08   10:2

[5000 rows x 19 columns]

#   <font color="cyan">Exporting the data</font>

In [58]:
df_a.to_csv('Autolib_dataset.csv')

#   <font color="cyan">Data Analysis</font>

Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

What station is the most popular?

In [60]:
df_a['City'].max()

'Ã\x89pinay-sur-Seine'

What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?

In [76]:
df_a['Bluecar counter'].max()
df_a['Address'][df_a['Bluecar counter']==7]

146                                22 Voie au Lard
245                    68 rue de la Bonne Aventure
534                            6 rue Isidore Nerat
584                              1 rue de l'Avenir
595                             16 avenue GalilÃ©e
603                             2 rue Paul Dautier
679                            29 rue Saint Stenay
803                                  7 rue Pottier
843                          14 place Moreau David
1106                              14 rue Lavoisier
1169                            16 avenue GalilÃ©e
1347                           194 rue de fontenay
1500              31 avenue de la Division Leclerc
1531                         14 place Moreau David
1782                                1 avenue Hoche
1845                            16 avenue GalilÃ©e
1985                      99 rue Charles-de-Gaulle
2039                       20 Rue Saint John Perse
2070                         40 Avenue Victor Hugo
2291                205 Avenue Georges ClÃ©menceau
2470                    2 rue du GÃ©nÃ©ral Renault
2670                   68 rue de la Bonne Aventure
2754                            16 avenue GalilÃ©e
3047                      1 allÃ©e Parc LagravÃ¨re
3115                    2 rue du GÃ©nÃ©ral Renault
3224                            16 avenue GalilÃ©e
3319                      99 rue Charles-de-Gaulle
3402                            16 avenue GalilÃ©e
3902              31 avenue de la Division Leclerc
3935                           11 rue de vincennes
3967    60 Avenue du PrÃ©sident Franklin Roosevelt
4085                            16 avenue GalilÃ©e
4568                205 Avenue Georges ClÃ©menceau
4571                204 rue dâEstienne dâOrves
4697                            2 rue Paul Dautier
4768                        3 avenue LÃ©o Lagrange
4806                          19 rue LÃ©on Renault
4839                           22 rue de Normandie
4865                         1 rue Claude Terrasse
Name: Address, dtype: object

In [71]:
df_a['City'][df_a['Bluecar counter']==7]

146                    Rungis
245                Versailles
534          Aulnay-sous-bois
584         Ãpinay-sur-Seine
595       Le Plessis-Robinson
603      VÃ©lizy-Villacoublay
679                    Drancy
803                Le Chesnay
843        Fontenay-Sous-Bois
1106                 Nanterre
1169      Le Plessis-Robinson
1347                Vincennes
1500       Fontenay-aux-Roses
1531       Fontenay-Sous-Bois
1782                 Nanterre
1845      Le Plessis-Robinson
1985                   Yerres
2039        Limeil-BrÃ©vannes
2070                  Clamart
2291                 Nanterre
2470                    Paris
2670               Versailles
2754      Le Plessis-Robinson
3047                 Colombes
3115                    Paris
3224      Le Plessis-Robinson
3319                   Yerres
3402      Le Plessis-Robinson
3902       Fontenay-aux-Roses
3935                Montreuil
3967                   Sceaux
4085      Le Plessis-Robinson
4568                 Nanterre
4571    VerriÃ¨res-le-Buisson
4697     VÃ©lizy-Villacoublay
4768                Montreuil
4806                Les Lilas
4839      AsniÃ¨res-sur-Seine
4865          Le Blanc-Mesnil
Name: City, dtype: object

Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars?

In [68]:
df_a['Utilib counter'].max()
df_a['Address'][df_a['Utilib counter']==2]

77       31 Boulevard Rochechouart
109        33 Avenue Jules Quentin
846           46 rue Armand Carrel
2429         161 Avenue de Suffren
2836             33 rue de Lourmel
2960             43 Rue de Monceau
3222            99 Boulevard Arago
3237              54 rue HÃ©ricart
3329       19 rue de Chateaubriand
3369         5 avenue Jean JaurÃ¨s
4064    17 rue Jean-Pierre Timbaud
4553          19 Rue de l'ArrivÃ©e
Name: Address, dtype: object

In [72]:
df_a['City'][df_a['Utilib counter']==2]

77                   Paris
109               Nanterre
846                  Paris
2429                 Paris
2836                 Paris
2960                 Paris
3222                 Paris
3237                 Paris
3329                 Paris
3369       Rosny-sous-Bois
4064    Fontenay-Sous-Bois
4553     Enghien-les-Bains
Name: City, dtype: object

In [70]:
df_a['Utilib 1.4 counter'].max()
df_a['Address'][df_a['Utilib 1.4 counter']== 3]

990     109 avenue FÃ©lix Faure
2731             123 Grande Rue
Name: Address, dtype: object

In [73]:
df_a['City'][df_a['Utilib 1.4 counter']== 3]

990       Paris
2731    SÃ¨vres
Name: City, dtype: object